[build]
  command = "cd esmer-market-website && npm install && npm run build"
  publish = "esmer-market-website/out"
  functions = "esmer-market-website/netlify/functions"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_VERSION = "10.5.2"
  NODE_OPTIONS = "--max_old_space_size=4096"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_FIREBASE_API_KEY,NEXT_PUBLIC_FIREBASE_APP_ID,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NEXT_PUBLIC_FIREBASE_PROJECT_ID,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NEXT_PUBLIC_RECAPTCHA_SITE_KEY"
